application: cbahacks
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /admin/.*
  script: admin.app
  login: required
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: portal.app

libraries:
- name: jinja2
  version: latest

admin_console:
  pages:
  - name: "Upload talk"
    url: /admin/upload_talk